name: Build

on:
  pull_request:
  push:
    branches:
      - dev
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/tinygo-org/tinygo-dev
    steps:
      - name: Work around CVE-2022-24765
        # We're not on a multi-user machine, so this is safe.
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v3
      - name: TinyGo version check
        run: tinygo version
      - name: Enforce Go Formatted Code
        run: make fmt-check
      - name: Run build and smoke tests
        run: make smoke-test
